### ISSUE TITLE
Cant login anymore

### ISSUE THREAD

**Issue by AsWali** [sembogaarts/Gymtime#2]
I am getting: Unable to login at Basic-Fit, when I paste the cookie.
I used to work for me but not anymore now. Any idea why ? Does it still work for you ?
And which values of the cookie are relevant ?

**Comment by sembogaarts** [comment]
You should use the `sid` cookie, I will look at the bug tomorow. You can also use this as a service at `gymtijd.nl`.

**Comment by AsWali** [comment]
Tested it again now. It works again.
