### ISSUE TITLE
can't connect, cookie too big

### ISSUE THREAD

**Issue by mathias-bradi** [sembogaarts/Gymtime#3]
my cookie seems to be too big to connect with 
the program is launching and then nothing append

**Comment by sembogaarts** [comment]
Thanks for creating the issue, I will check this tonight!

**Comment by wouterheylen** [comment]
I installed the app but get stuck in:
```
File "..\main.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by jensvannerum** [comment]
> Thanks for creating the issue, I will check this tonight!

Did you ever fix this? Same problem trying to make something similiar in Java

**Comment by simlf** [comment]
Hello, did you manage to fix that issue ? If you want I can try to check from where does the problem comes from

**Comment by sembogaarts** [comment]
Might have found a way to get around the captcha so you can login with your credentials via the CLI, I try to implement this!

**Comment by jensvannerum** [comment]
> 

I just get the cookie from the browser (I made this in Java) using login

**Comment by sembogaarts** [comment]
Hi everyone! Just pushed a whole new version. I found a way to get around the captcha, it's now possible to enter your credentials. I updated the README with more details.

I'll close this issue because using the cookie is no longer supported.
